### ISSUE TITLE
ROS 

### ISSUE THREAD

**Issue by asuleyman** [maudzung/SFA3D#44]
I get the following error when I run rosrun super_fast_object_detection rosInference.py

[ERROR] [1622813649.547097]: bad callback: <function on_scan at 0x7fafb9fdef70>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/ahmed/PCL_OD/SFA3D/ros/src/super_fast_object_detection/src/rosInference.py", line 63, in on_scan
    bev_map = makeBEVMap(front_lidar, cnf.boundary)
  File "/home/ahmed/PCL_OD/SFA3D/sfa/data_process/kitti_bev_utils.py", line 34, in makeBEVMap
    _, unique_indices, unique_counts = np.unique(PointCloud[:, 0:2], axis=0, return_index=True, return_counts=True)
  File "<__array_function__ internals>", line 5, in unique
  File "/home/ahmed/anaconda3/lib/python3.8/site-packages/numpy/lib/arraysetops.py", line 275, in unique
    ar = ar.reshape(orig_shape[0], -1)
ValueError: cannot reshape array of size 0 into shape (0,newaxis)

Any tips to resolve the error?

**Comment by urbansound8K** [comment]
could you find ROS documentation?
the page is not working anymore!!!

**Comment by maudzung** [comment]
For ROS implementation, please contact @AhmedARadwan to get instructions. Many thanks
