### ISSUE TITLE
AttributeError: module 'rospkg' has no attribute 'RosPack'

### ISSUE THREAD

**Issue by vidit2011998** [maudzung/SFA3D#55]

**Comment by vidit2011998** [comment]
Hi everyone, I am facing this issue. Did all steps but still this error:
Traceback (most recent call last):
  File "/home/vidit/Downloads/SFA3D/ros/src/super_fast_object_detection/src/rosInference.py", line 2, in <module>
    import sensor_msgs.point_cloud2 as pc2
  File "/opt/ros/melodic/lib/python2.7/dist-packages/sensor_msgs/point_cloud2.py", line 48, in <module>
    import roslib.message
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/__init__.py", line 50, in <module>
    from roslib.launcher import load_manifest  # noqa: F401
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/launcher.py", line 48, in <module>
    _rospack = rospkg.RosPack()
AttributeError: module 'rospkg' has no attribute 'RosPack'

**Comment by maudzung** [comment]
For ROS implementation, please contact @AhmedARadwan to get instructions. Many thanks
